### ISSUE TITLE
Feature Request: Velocity Support

### ISSUE THREAD

**Issue by TechnicallyCoded** [MrUniverse44/PixelMOTD3#2]
Easier said than done, but I would suggest adding velocity as a supported platform. Waterfall will soon be deprecated and most people / big servers will move away from the bungeecord system. It would be nice to have pixel motd along for the ride ^^

**Comment by OopsieWoopsie** [comment]
> Waterfall will soon be deprecated and most people / big servers will move away from the bungeecord system.

Fuente: miami me lo confirmo

**Comment by MrUniverse44** [comment]
I'm already working on it ;)

**Comment by TechnicallyCoded** [comment]
<3
